// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/util/message_differencer_unittest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto;
namespace protobuf_unittest {
class TestDiffMessage;
class TestDiffMessageDefaultTypeInternal;
extern TestDiffMessageDefaultTypeInternal _TestDiffMessage_default_instance_;
class TestDiffMessage_Item;
class TestDiffMessage_ItemDefaultTypeInternal;
extern TestDiffMessage_ItemDefaultTypeInternal _TestDiffMessage_Item_default_instance_;
class TestField;
class TestFieldDefaultTypeInternal;
extern TestFieldDefaultTypeInternal _TestField_default_instance_;
}  // namespace protobuf_unittest
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf_unittest::TestDiffMessage* Arena::CreateMaybeMessage<::protobuf_unittest::TestDiffMessage>(Arena*);
template<> ::protobuf_unittest::TestDiffMessage_Item* Arena::CreateMaybeMessage<::protobuf_unittest::TestDiffMessage_Item>(Arena*);
template<> ::protobuf_unittest::TestField* Arena::CreateMaybeMessage<::protobuf_unittest::TestField>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf_unittest {

// ===================================================================

class TestField :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf_unittest.TestField) */ {
 public:
  TestField();
  virtual ~TestField();

  TestField(const TestField& from);
  TestField(TestField&& from) noexcept
    : TestField() {
    *this = ::std::move(from);
  }

  inline TestField& operator=(const TestField& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestField& operator=(TestField&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TestField& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestField* internal_default_instance() {
    return reinterpret_cast<const TestField*>(
               &_TestField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TestField& a, TestField& b) {
    a.Swap(&b);
  }
  inline void Swap(TestField* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TestField* New() const final {
    return CreateMaybeMessage<TestField>(nullptr);
  }

  TestField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TestField>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TestField& from);
  void MergeFrom(const TestField& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestField* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf_unittest.TestField";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto);
    return ::descriptor_table_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRcFieldNumber = 2,
    kMFieldNumber = 5,
    kCFieldNumber = 1,
    kAFieldNumber = 3,
    kBFieldNumber = 4,
  };
  // repeated int32 rc = 2;
  int rc_size() const;
  private:
  int _internal_rc_size() const;
  public:
  void clear_rc();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rc(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_rc() const;
  void _internal_add_rc(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_rc();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 rc(int index) const;
  void set_rc(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_rc(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      rc() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_rc();

  // optional .protobuf_unittest.TestField m = 5;
  bool has_m() const;
  private:
  bool _internal_has_m() const;
  public:
  void clear_m();
  const ::protobuf_unittest::TestField& m() const;
  ::protobuf_unittest::TestField* release_m();
  ::protobuf_unittest::TestField* mutable_m();
  void set_allocated_m(::protobuf_unittest::TestField* m);
  private:
  const ::protobuf_unittest::TestField& _internal_m() const;
  ::protobuf_unittest::TestField* _internal_mutable_m();
  public:

  // optional int32 c = 1;
  bool has_c() const;
  private:
  bool _internal_has_c() const;
  public:
  void clear_c();
  ::PROTOBUF_NAMESPACE_ID::int32 c() const;
  void set_c(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_c() const;
  void _internal_set_c(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 a = 3;
  bool has_a() const;
  private:
  bool _internal_has_a() const;
  public:
  void clear_a();
  ::PROTOBUF_NAMESPACE_ID::int32 a() const;
  void set_a(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_a() const;
  void _internal_set_a(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 b = 4;
  bool has_b() const;
  private:
  bool _internal_has_b() const;
  public:
  void clear_b();
  ::PROTOBUF_NAMESPACE_ID::int32 b() const;
  void set_b(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_b() const;
  void _internal_set_b(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  static const int kTfFieldNumber = 100;
  static ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::protobuf_unittest::TestDiffMessage,
      ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::protobuf_unittest::TestField >, 11, false >
    tf;
  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestField)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > rc_;
  ::protobuf_unittest::TestField* m_;
  ::PROTOBUF_NAMESPACE_ID::int32 c_;
  ::PROTOBUF_NAMESPACE_ID::int32 a_;
  ::PROTOBUF_NAMESPACE_ID::int32 b_;
  friend struct ::TableStruct_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto;
};
// -------------------------------------------------------------------

class TestDiffMessage_Item :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf_unittest.TestDiffMessage.Item) */ {
 public:
  TestDiffMessage_Item();
  virtual ~TestDiffMessage_Item();

  TestDiffMessage_Item(const TestDiffMessage_Item& from);
  TestDiffMessage_Item(TestDiffMessage_Item&& from) noexcept
    : TestDiffMessage_Item() {
    *this = ::std::move(from);
  }

  inline TestDiffMessage_Item& operator=(const TestDiffMessage_Item& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestDiffMessage_Item& operator=(TestDiffMessage_Item&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TestDiffMessage_Item& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestDiffMessage_Item* internal_default_instance() {
    return reinterpret_cast<const TestDiffMessage_Item*>(
               &_TestDiffMessage_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TestDiffMessage_Item& a, TestDiffMessage_Item& b) {
    a.Swap(&b);
  }
  inline void Swap(TestDiffMessage_Item* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TestDiffMessage_Item* New() const final {
    return CreateMaybeMessage<TestDiffMessage_Item>(nullptr);
  }

  TestDiffMessage_Item* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TestDiffMessage_Item>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TestDiffMessage_Item& from);
  void MergeFrom(const TestDiffMessage_Item& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestDiffMessage_Item* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf_unittest.TestDiffMessage.Item";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto);
    return ::descriptor_table_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRaFieldNumber = 3,
    kRbFieldNumber = 5,
    kRmFieldNumber = 7,
    kBFieldNumber = 4,
    kMFieldNumber = 6,
    kAFieldNumber = 2,
  };
  // repeated int32 ra = 3;
  int ra_size() const;
  private:
  int _internal_ra_size() const;
  public:
  void clear_ra();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ra(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_ra() const;
  void _internal_add_ra(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_ra();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 ra(int index) const;
  void set_ra(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_ra(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      ra() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_ra();

  // repeated string rb = 5;
  int rb_size() const;
  private:
  int _internal_rb_size() const;
  public:
  void clear_rb();
  const std::string& rb(int index) const;
  std::string* mutable_rb(int index);
  void set_rb(int index, const std::string& value);
  void set_rb(int index, std::string&& value);
  void set_rb(int index, const char* value);
  void set_rb(int index, const char* value, size_t size);
  std::string* add_rb();
  void add_rb(const std::string& value);
  void add_rb(std::string&& value);
  void add_rb(const char* value);
  void add_rb(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& rb() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_rb();
  private:
  const std::string& _internal_rb(int index) const;
  std::string* _internal_add_rb();
  public:

  // repeated .protobuf_unittest.TestField rm = 7;
  int rm_size() const;
  private:
  int _internal_rm_size() const;
  public:
  void clear_rm();
  ::protobuf_unittest::TestField* mutable_rm(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >*
      mutable_rm();
  private:
  const ::protobuf_unittest::TestField& _internal_rm(int index) const;
  ::protobuf_unittest::TestField* _internal_add_rm();
  public:
  const ::protobuf_unittest::TestField& rm(int index) const;
  ::protobuf_unittest::TestField* add_rm();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >&
      rm() const;

  // optional string b = 4;
  bool has_b() const;
  private:
  bool _internal_has_b() const;
  public:
  void clear_b();
  const std::string& b() const;
  void set_b(const std::string& value);
  void set_b(std::string&& value);
  void set_b(const char* value);
  void set_b(const char* value, size_t size);
  std::string* mutable_b();
  std::string* release_b();
  void set_allocated_b(std::string* b);
  private:
  const std::string& _internal_b() const;
  void _internal_set_b(const std::string& value);
  std::string* _internal_mutable_b();
  public:

  // optional .protobuf_unittest.TestField m = 6;
  bool has_m() const;
  private:
  bool _internal_has_m() const;
  public:
  void clear_m();
  const ::protobuf_unittest::TestField& m() const;
  ::protobuf_unittest::TestField* release_m();
  ::protobuf_unittest::TestField* mutable_m();
  void set_allocated_m(::protobuf_unittest::TestField* m);
  private:
  const ::protobuf_unittest::TestField& _internal_m() const;
  ::protobuf_unittest::TestField* _internal_mutable_m();
  public:

  // optional int32 a = 2;
  bool has_a() const;
  private:
  bool _internal_has_a() const;
  public:
  void clear_a();
  ::PROTOBUF_NAMESPACE_ID::int32 a() const;
  void set_a(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_a() const;
  void _internal_set_a(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestDiffMessage.Item)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > ra_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> rb_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField > rm_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr b_;
  ::protobuf_unittest::TestField* m_;
  ::PROTOBUF_NAMESPACE_ID::int32 a_;
  friend struct ::TableStruct_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto;
};
// -------------------------------------------------------------------

class TestDiffMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf_unittest.TestDiffMessage) */ {
 public:
  TestDiffMessage();
  virtual ~TestDiffMessage();

  TestDiffMessage(const TestDiffMessage& from);
  TestDiffMessage(TestDiffMessage&& from) noexcept
    : TestDiffMessage() {
    *this = ::std::move(from);
  }

  inline TestDiffMessage& operator=(const TestDiffMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestDiffMessage& operator=(TestDiffMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TestDiffMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestDiffMessage* internal_default_instance() {
    return reinterpret_cast<const TestDiffMessage*>(
               &_TestDiffMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TestDiffMessage& a, TestDiffMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(TestDiffMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TestDiffMessage* New() const final {
    return CreateMaybeMessage<TestDiffMessage>(nullptr);
  }

  TestDiffMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TestDiffMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TestDiffMessage& from);
  void MergeFrom(const TestDiffMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestDiffMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf_unittest.TestDiffMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto);
    return ::descriptor_table_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef TestDiffMessage_Item Item;

  // accessors -------------------------------------------------------

  enum : int {
    kItemFieldNumber = 1,
    kRwFieldNumber = 10,
    kRvFieldNumber = 11,
    kRmFieldNumber = 12,
    kRanyFieldNumber = 16,
    kWFieldNumber = 14,
    kMFieldNumber = 15,
    kVFieldNumber = 13,
  };
  // repeated group Item = 1 { ... };
  int item_size() const;
  private:
  int _internal_item_size() const;
  public:
  void clear_item();
  ::protobuf_unittest::TestDiffMessage_Item* mutable_item(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestDiffMessage_Item >*
      mutable_item();
  private:
  const ::protobuf_unittest::TestDiffMessage_Item& _internal_item(int index) const;
  ::protobuf_unittest::TestDiffMessage_Item* _internal_add_item();
  public:
  const ::protobuf_unittest::TestDiffMessage_Item& item(int index) const;
  ::protobuf_unittest::TestDiffMessage_Item* add_item();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestDiffMessage_Item >&
      item() const;

  // repeated string rw = 10;
  int rw_size() const;
  private:
  int _internal_rw_size() const;
  public:
  void clear_rw();
  const std::string& rw(int index) const;
  std::string* mutable_rw(int index);
  void set_rw(int index, const std::string& value);
  void set_rw(int index, std::string&& value);
  void set_rw(int index, const char* value);
  void set_rw(int index, const char* value, size_t size);
  std::string* add_rw();
  void add_rw(const std::string& value);
  void add_rw(std::string&& value);
  void add_rw(const char* value);
  void add_rw(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& rw() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_rw();
  private:
  const std::string& _internal_rw(int index) const;
  std::string* _internal_add_rw();
  public:

  // repeated int32 rv = 11;
  int rv_size() const;
  private:
  int _internal_rv_size() const;
  public:
  void clear_rv();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rv(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_rv() const;
  void _internal_add_rv(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_rv();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 rv(int index) const;
  void set_rv(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_rv(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      rv() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_rv();

  // repeated .protobuf_unittest.TestField rm = 12 [deprecated = true];
  PROTOBUF_DEPRECATED int rm_size() const;
  private:
  int _internal_rm_size() const;
  public:
  PROTOBUF_DEPRECATED void clear_rm();
  PROTOBUF_DEPRECATED ::protobuf_unittest::TestField* mutable_rm(int index);
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >*
      mutable_rm();
  private:
  const ::protobuf_unittest::TestField& _internal_rm(int index) const;
  ::protobuf_unittest::TestField* _internal_add_rm();
  public:
  PROTOBUF_DEPRECATED const ::protobuf_unittest::TestField& rm(int index) const;
  PROTOBUF_DEPRECATED ::protobuf_unittest::TestField* add_rm();
  PROTOBUF_DEPRECATED const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >&
      rm() const;

  // repeated .google.protobuf.Any rany = 16;
  int rany_size() const;
  private:
  int _internal_rany_size() const;
  public:
  void clear_rany();
  PROTOBUF_NAMESPACE_ID::Any* mutable_rany(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::Any >*
      mutable_rany();
  private:
  const PROTOBUF_NAMESPACE_ID::Any& _internal_rany(int index) const;
  PROTOBUF_NAMESPACE_ID::Any* _internal_add_rany();
  public:
  const PROTOBUF_NAMESPACE_ID::Any& rany(int index) const;
  PROTOBUF_NAMESPACE_ID::Any* add_rany();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::Any >&
      rany() const;

  // optional string w = 14;
  bool has_w() const;
  private:
  bool _internal_has_w() const;
  public:
  void clear_w();
  const std::string& w() const;
  void set_w(const std::string& value);
  void set_w(std::string&& value);
  void set_w(const char* value);
  void set_w(const char* value, size_t size);
  std::string* mutable_w();
  std::string* release_w();
  void set_allocated_w(std::string* w);
  private:
  const std::string& _internal_w() const;
  void _internal_set_w(const std::string& value);
  std::string* _internal_mutable_w();
  public:

  // optional .protobuf_unittest.TestField m = 15;
  bool has_m() const;
  private:
  bool _internal_has_m() const;
  public:
  void clear_m();
  const ::protobuf_unittest::TestField& m() const;
  ::protobuf_unittest::TestField* release_m();
  ::protobuf_unittest::TestField* mutable_m();
  void set_allocated_m(::protobuf_unittest::TestField* m);
  private:
  const ::protobuf_unittest::TestField& _internal_m() const;
  ::protobuf_unittest::TestField* _internal_mutable_m();
  public:

  // optional int32 v = 13 [deprecated = true];
  PROTOBUF_DEPRECATED bool has_v() const;
  private:
  bool _internal_has_v() const;
  public:
  PROTOBUF_DEPRECATED void clear_v();
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int32 v() const;
  PROTOBUF_DEPRECATED void set_v(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_v() const;
  void _internal_set_v(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(TestDiffMessage)
  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestDiffMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::ExtensionSet _extensions_;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestDiffMessage_Item > item_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> rw_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > rv_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField > rm_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::Any > rany_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr w_;
  ::protobuf_unittest::TestField* m_;
  ::PROTOBUF_NAMESPACE_ID::int32 v_;
  friend struct ::TableStruct_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestField

// optional int32 a = 3;
inline bool TestField::_internal_has_a() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TestField::has_a() const {
  return _internal_has_a();
}
inline void TestField::clear_a() {
  a_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::_internal_a() const {
  return a_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::a() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestField.a)
  return _internal_a();
}
inline void TestField::_internal_set_a(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  a_ = value;
}
inline void TestField::set_a(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_a(value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestField.a)
}

// optional int32 b = 4;
inline bool TestField::_internal_has_b() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TestField::has_b() const {
  return _internal_has_b();
}
inline void TestField::clear_b() {
  b_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::_internal_b() const {
  return b_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::b() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestField.b)
  return _internal_b();
}
inline void TestField::_internal_set_b(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  b_ = value;
}
inline void TestField::set_b(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestField.b)
}

// optional int32 c = 1;
inline bool TestField::_internal_has_c() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TestField::has_c() const {
  return _internal_has_c();
}
inline void TestField::clear_c() {
  c_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::_internal_c() const {
  return c_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::c() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestField.c)
  return _internal_c();
}
inline void TestField::_internal_set_c(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  c_ = value;
}
inline void TestField::set_c(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_c(value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestField.c)
}

// repeated int32 rc = 2;
inline int TestField::_internal_rc_size() const {
  return rc_.size();
}
inline int TestField::rc_size() const {
  return _internal_rc_size();
}
inline void TestField::clear_rc() {
  rc_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::_internal_rc(int index) const {
  return rc_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestField::rc(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestField.rc)
  return _internal_rc(index);
}
inline void TestField::set_rc(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  rc_.Set(index, value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestField.rc)
}
inline void TestField::_internal_add_rc(::PROTOBUF_NAMESPACE_ID::int32 value) {
  rc_.Add(value);
}
inline void TestField::add_rc(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_rc(value);
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestField.rc)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TestField::_internal_rc() const {
  return rc_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TestField::rc() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestField.rc)
  return _internal_rc();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TestField::_internal_mutable_rc() {
  return &rc_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TestField::mutable_rc() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestField.rc)
  return _internal_mutable_rc();
}

// optional .protobuf_unittest.TestField m = 5;
inline bool TestField::_internal_has_m() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || m_ != nullptr);
  return value;
}
inline bool TestField::has_m() const {
  return _internal_has_m();
}
inline void TestField::clear_m() {
  if (m_ != nullptr) m_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::protobuf_unittest::TestField& TestField::_internal_m() const {
  const ::protobuf_unittest::TestField* p = m_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protobuf_unittest::TestField*>(
      &::protobuf_unittest::_TestField_default_instance_);
}
inline const ::protobuf_unittest::TestField& TestField::m() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestField.m)
  return _internal_m();
}
inline ::protobuf_unittest::TestField* TestField::release_m() {
  // @@protoc_insertion_point(field_release:protobuf_unittest.TestField.m)
  _has_bits_[0] &= ~0x00000001u;
  ::protobuf_unittest::TestField* temp = m_;
  m_ = nullptr;
  return temp;
}
inline ::protobuf_unittest::TestField* TestField::_internal_mutable_m() {
  _has_bits_[0] |= 0x00000001u;
  if (m_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf_unittest::TestField>(GetArenaNoVirtual());
    m_ = p;
  }
  return m_;
}
inline ::protobuf_unittest::TestField* TestField::mutable_m() {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestField.m)
  return _internal_mutable_m();
}
inline void TestField::set_allocated_m(::protobuf_unittest::TestField* m) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete m_;
  }
  if (m) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      m = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  m_ = m;
  // @@protoc_insertion_point(field_set_allocated:protobuf_unittest.TestField.m)
}

// -------------------------------------------------------------------

// TestDiffMessage_Item

// optional int32 a = 2;
inline bool TestDiffMessage_Item::_internal_has_a() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TestDiffMessage_Item::has_a() const {
  return _internal_has_a();
}
inline void TestDiffMessage_Item::clear_a() {
  a_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage_Item::_internal_a() const {
  return a_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage_Item::a() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.Item.a)
  return _internal_a();
}
inline void TestDiffMessage_Item::_internal_set_a(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  a_ = value;
}
inline void TestDiffMessage_Item::set_a(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_a(value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.Item.a)
}

// optional string b = 4;
inline bool TestDiffMessage_Item::_internal_has_b() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TestDiffMessage_Item::has_b() const {
  return _internal_has_b();
}
inline void TestDiffMessage_Item::clear_b() {
  b_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TestDiffMessage_Item::b() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.Item.b)
  return _internal_b();
}
inline void TestDiffMessage_Item::set_b(const std::string& value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.Item.b)
}
inline std::string* TestDiffMessage_Item::mutable_b() {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.Item.b)
  return _internal_mutable_b();
}
inline const std::string& TestDiffMessage_Item::_internal_b() const {
  return b_.GetNoArena();
}
inline void TestDiffMessage_Item::_internal_set_b(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  b_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TestDiffMessage_Item::set_b(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  b_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protobuf_unittest.TestDiffMessage.Item.b)
}
inline void TestDiffMessage_Item::set_b(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  b_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protobuf_unittest.TestDiffMessage.Item.b)
}
inline void TestDiffMessage_Item::set_b(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  b_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protobuf_unittest.TestDiffMessage.Item.b)
}
inline std::string* TestDiffMessage_Item::_internal_mutable_b() {
  _has_bits_[0] |= 0x00000001u;
  return b_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TestDiffMessage_Item::release_b() {
  // @@protoc_insertion_point(field_release:protobuf_unittest.TestDiffMessage.Item.b)
  if (!has_b()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return b_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TestDiffMessage_Item::set_allocated_b(std::string* b) {
  if (b != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  b_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), b);
  // @@protoc_insertion_point(field_set_allocated:protobuf_unittest.TestDiffMessage.Item.b)
}

// repeated int32 ra = 3;
inline int TestDiffMessage_Item::_internal_ra_size() const {
  return ra_.size();
}
inline int TestDiffMessage_Item::ra_size() const {
  return _internal_ra_size();
}
inline void TestDiffMessage_Item::clear_ra() {
  ra_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage_Item::_internal_ra(int index) const {
  return ra_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage_Item::ra(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.Item.ra)
  return _internal_ra(index);
}
inline void TestDiffMessage_Item::set_ra(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  ra_.Set(index, value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.Item.ra)
}
inline void TestDiffMessage_Item::_internal_add_ra(::PROTOBUF_NAMESPACE_ID::int32 value) {
  ra_.Add(value);
}
inline void TestDiffMessage_Item::add_ra(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_ra(value);
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.Item.ra)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TestDiffMessage_Item::_internal_ra() const {
  return ra_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TestDiffMessage_Item::ra() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.Item.ra)
  return _internal_ra();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TestDiffMessage_Item::_internal_mutable_ra() {
  return &ra_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TestDiffMessage_Item::mutable_ra() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.Item.ra)
  return _internal_mutable_ra();
}

// repeated string rb = 5;
inline int TestDiffMessage_Item::_internal_rb_size() const {
  return rb_.size();
}
inline int TestDiffMessage_Item::rb_size() const {
  return _internal_rb_size();
}
inline void TestDiffMessage_Item::clear_rb() {
  rb_.Clear();
}
inline std::string* TestDiffMessage_Item::add_rb() {
  // @@protoc_insertion_point(field_add_mutable:protobuf_unittest.TestDiffMessage.Item.rb)
  return _internal_add_rb();
}
inline const std::string& TestDiffMessage_Item::_internal_rb(int index) const {
  return rb_.Get(index);
}
inline const std::string& TestDiffMessage_Item::rb(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.Item.rb)
  return _internal_rb(index);
}
inline std::string* TestDiffMessage_Item::mutable_rb(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.Item.rb)
  return rb_.Mutable(index);
}
inline void TestDiffMessage_Item::set_rb(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.Item.rb)
  rb_.Mutable(index)->assign(value);
}
inline void TestDiffMessage_Item::set_rb(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.Item.rb)
  rb_.Mutable(index)->assign(std::move(value));
}
inline void TestDiffMessage_Item::set_rb(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  rb_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protobuf_unittest.TestDiffMessage.Item.rb)
}
inline void TestDiffMessage_Item::set_rb(int index, const char* value, size_t size) {
  rb_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protobuf_unittest.TestDiffMessage.Item.rb)
}
inline std::string* TestDiffMessage_Item::_internal_add_rb() {
  return rb_.Add();
}
inline void TestDiffMessage_Item::add_rb(const std::string& value) {
  rb_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.Item.rb)
}
inline void TestDiffMessage_Item::add_rb(std::string&& value) {
  rb_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.Item.rb)
}
inline void TestDiffMessage_Item::add_rb(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  rb_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protobuf_unittest.TestDiffMessage.Item.rb)
}
inline void TestDiffMessage_Item::add_rb(const char* value, size_t size) {
  rb_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protobuf_unittest.TestDiffMessage.Item.rb)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TestDiffMessage_Item::rb() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.Item.rb)
  return rb_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TestDiffMessage_Item::mutable_rb() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.Item.rb)
  return &rb_;
}

// optional .protobuf_unittest.TestField m = 6;
inline bool TestDiffMessage_Item::_internal_has_m() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || m_ != nullptr);
  return value;
}
inline bool TestDiffMessage_Item::has_m() const {
  return _internal_has_m();
}
inline void TestDiffMessage_Item::clear_m() {
  if (m_ != nullptr) m_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::protobuf_unittest::TestField& TestDiffMessage_Item::_internal_m() const {
  const ::protobuf_unittest::TestField* p = m_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protobuf_unittest::TestField*>(
      &::protobuf_unittest::_TestField_default_instance_);
}
inline const ::protobuf_unittest::TestField& TestDiffMessage_Item::m() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.Item.m)
  return _internal_m();
}
inline ::protobuf_unittest::TestField* TestDiffMessage_Item::release_m() {
  // @@protoc_insertion_point(field_release:protobuf_unittest.TestDiffMessage.Item.m)
  _has_bits_[0] &= ~0x00000002u;
  ::protobuf_unittest::TestField* temp = m_;
  m_ = nullptr;
  return temp;
}
inline ::protobuf_unittest::TestField* TestDiffMessage_Item::_internal_mutable_m() {
  _has_bits_[0] |= 0x00000002u;
  if (m_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf_unittest::TestField>(GetArenaNoVirtual());
    m_ = p;
  }
  return m_;
}
inline ::protobuf_unittest::TestField* TestDiffMessage_Item::mutable_m() {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.Item.m)
  return _internal_mutable_m();
}
inline void TestDiffMessage_Item::set_allocated_m(::protobuf_unittest::TestField* m) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete m_;
  }
  if (m) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      m = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  m_ = m;
  // @@protoc_insertion_point(field_set_allocated:protobuf_unittest.TestDiffMessage.Item.m)
}

// repeated .protobuf_unittest.TestField rm = 7;
inline int TestDiffMessage_Item::_internal_rm_size() const {
  return rm_.size();
}
inline int TestDiffMessage_Item::rm_size() const {
  return _internal_rm_size();
}
inline void TestDiffMessage_Item::clear_rm() {
  rm_.Clear();
}
inline ::protobuf_unittest::TestField* TestDiffMessage_Item::mutable_rm(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.Item.rm)
  return rm_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >*
TestDiffMessage_Item::mutable_rm() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.Item.rm)
  return &rm_;
}
inline const ::protobuf_unittest::TestField& TestDiffMessage_Item::_internal_rm(int index) const {
  return rm_.Get(index);
}
inline const ::protobuf_unittest::TestField& TestDiffMessage_Item::rm(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.Item.rm)
  return _internal_rm(index);
}
inline ::protobuf_unittest::TestField* TestDiffMessage_Item::_internal_add_rm() {
  return rm_.Add();
}
inline ::protobuf_unittest::TestField* TestDiffMessage_Item::add_rm() {
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.Item.rm)
  return _internal_add_rm();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >&
TestDiffMessage_Item::rm() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.Item.rm)
  return rm_;
}

// -------------------------------------------------------------------

// TestDiffMessage

// repeated group Item = 1 { ... };
inline int TestDiffMessage::_internal_item_size() const {
  return item_.size();
}
inline int TestDiffMessage::item_size() const {
  return _internal_item_size();
}
inline void TestDiffMessage::clear_item() {
  item_.Clear();
}
inline ::protobuf_unittest::TestDiffMessage_Item* TestDiffMessage::mutable_item(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.item)
  return item_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestDiffMessage_Item >*
TestDiffMessage::mutable_item() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.item)
  return &item_;
}
inline const ::protobuf_unittest::TestDiffMessage_Item& TestDiffMessage::_internal_item(int index) const {
  return item_.Get(index);
}
inline const ::protobuf_unittest::TestDiffMessage_Item& TestDiffMessage::item(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.item)
  return _internal_item(index);
}
inline ::protobuf_unittest::TestDiffMessage_Item* TestDiffMessage::_internal_add_item() {
  return item_.Add();
}
inline ::protobuf_unittest::TestDiffMessage_Item* TestDiffMessage::add_item() {
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.item)
  return _internal_add_item();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestDiffMessage_Item >&
TestDiffMessage::item() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.item)
  return item_;
}

// optional int32 v = 13 [deprecated = true];
inline bool TestDiffMessage::_internal_has_v() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TestDiffMessage::has_v() const {
  return _internal_has_v();
}
inline void TestDiffMessage::clear_v() {
  v_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage::_internal_v() const {
  return v_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage::v() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.v)
  return _internal_v();
}
inline void TestDiffMessage::_internal_set_v(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  v_ = value;
}
inline void TestDiffMessage::set_v(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_v(value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.v)
}

// optional string w = 14;
inline bool TestDiffMessage::_internal_has_w() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TestDiffMessage::has_w() const {
  return _internal_has_w();
}
inline void TestDiffMessage::clear_w() {
  w_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TestDiffMessage::w() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.w)
  return _internal_w();
}
inline void TestDiffMessage::set_w(const std::string& value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.w)
}
inline std::string* TestDiffMessage::mutable_w() {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.w)
  return _internal_mutable_w();
}
inline const std::string& TestDiffMessage::_internal_w() const {
  return w_.GetNoArena();
}
inline void TestDiffMessage::_internal_set_w(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  w_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TestDiffMessage::set_w(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  w_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protobuf_unittest.TestDiffMessage.w)
}
inline void TestDiffMessage::set_w(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  w_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protobuf_unittest.TestDiffMessage.w)
}
inline void TestDiffMessage::set_w(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  w_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protobuf_unittest.TestDiffMessage.w)
}
inline std::string* TestDiffMessage::_internal_mutable_w() {
  _has_bits_[0] |= 0x00000001u;
  return w_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TestDiffMessage::release_w() {
  // @@protoc_insertion_point(field_release:protobuf_unittest.TestDiffMessage.w)
  if (!has_w()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return w_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TestDiffMessage::set_allocated_w(std::string* w) {
  if (w != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  w_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), w);
  // @@protoc_insertion_point(field_set_allocated:protobuf_unittest.TestDiffMessage.w)
}

// optional .protobuf_unittest.TestField m = 15;
inline bool TestDiffMessage::_internal_has_m() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || m_ != nullptr);
  return value;
}
inline bool TestDiffMessage::has_m() const {
  return _internal_has_m();
}
inline void TestDiffMessage::clear_m() {
  if (m_ != nullptr) m_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::protobuf_unittest::TestField& TestDiffMessage::_internal_m() const {
  const ::protobuf_unittest::TestField* p = m_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protobuf_unittest::TestField*>(
      &::protobuf_unittest::_TestField_default_instance_);
}
inline const ::protobuf_unittest::TestField& TestDiffMessage::m() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.m)
  return _internal_m();
}
inline ::protobuf_unittest::TestField* TestDiffMessage::release_m() {
  // @@protoc_insertion_point(field_release:protobuf_unittest.TestDiffMessage.m)
  _has_bits_[0] &= ~0x00000002u;
  ::protobuf_unittest::TestField* temp = m_;
  m_ = nullptr;
  return temp;
}
inline ::protobuf_unittest::TestField* TestDiffMessage::_internal_mutable_m() {
  _has_bits_[0] |= 0x00000002u;
  if (m_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf_unittest::TestField>(GetArenaNoVirtual());
    m_ = p;
  }
  return m_;
}
inline ::protobuf_unittest::TestField* TestDiffMessage::mutable_m() {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.m)
  return _internal_mutable_m();
}
inline void TestDiffMessage::set_allocated_m(::protobuf_unittest::TestField* m) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete m_;
  }
  if (m) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      m = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  m_ = m;
  // @@protoc_insertion_point(field_set_allocated:protobuf_unittest.TestDiffMessage.m)
}

// repeated int32 rv = 11;
inline int TestDiffMessage::_internal_rv_size() const {
  return rv_.size();
}
inline int TestDiffMessage::rv_size() const {
  return _internal_rv_size();
}
inline void TestDiffMessage::clear_rv() {
  rv_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage::_internal_rv(int index) const {
  return rv_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TestDiffMessage::rv(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.rv)
  return _internal_rv(index);
}
inline void TestDiffMessage::set_rv(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  rv_.Set(index, value);
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.rv)
}
inline void TestDiffMessage::_internal_add_rv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  rv_.Add(value);
}
inline void TestDiffMessage::add_rv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_rv(value);
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.rv)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TestDiffMessage::_internal_rv() const {
  return rv_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TestDiffMessage::rv() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.rv)
  return _internal_rv();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TestDiffMessage::_internal_mutable_rv() {
  return &rv_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TestDiffMessage::mutable_rv() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.rv)
  return _internal_mutable_rv();
}

// repeated string rw = 10;
inline int TestDiffMessage::_internal_rw_size() const {
  return rw_.size();
}
inline int TestDiffMessage::rw_size() const {
  return _internal_rw_size();
}
inline void TestDiffMessage::clear_rw() {
  rw_.Clear();
}
inline std::string* TestDiffMessage::add_rw() {
  // @@protoc_insertion_point(field_add_mutable:protobuf_unittest.TestDiffMessage.rw)
  return _internal_add_rw();
}
inline const std::string& TestDiffMessage::_internal_rw(int index) const {
  return rw_.Get(index);
}
inline const std::string& TestDiffMessage::rw(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.rw)
  return _internal_rw(index);
}
inline std::string* TestDiffMessage::mutable_rw(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.rw)
  return rw_.Mutable(index);
}
inline void TestDiffMessage::set_rw(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.rw)
  rw_.Mutable(index)->assign(value);
}
inline void TestDiffMessage::set_rw(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:protobuf_unittest.TestDiffMessage.rw)
  rw_.Mutable(index)->assign(std::move(value));
}
inline void TestDiffMessage::set_rw(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  rw_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protobuf_unittest.TestDiffMessage.rw)
}
inline void TestDiffMessage::set_rw(int index, const char* value, size_t size) {
  rw_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protobuf_unittest.TestDiffMessage.rw)
}
inline std::string* TestDiffMessage::_internal_add_rw() {
  return rw_.Add();
}
inline void TestDiffMessage::add_rw(const std::string& value) {
  rw_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.rw)
}
inline void TestDiffMessage::add_rw(std::string&& value) {
  rw_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.rw)
}
inline void TestDiffMessage::add_rw(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  rw_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protobuf_unittest.TestDiffMessage.rw)
}
inline void TestDiffMessage::add_rw(const char* value, size_t size) {
  rw_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protobuf_unittest.TestDiffMessage.rw)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TestDiffMessage::rw() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.rw)
  return rw_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TestDiffMessage::mutable_rw() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.rw)
  return &rw_;
}

// repeated .protobuf_unittest.TestField rm = 12 [deprecated = true];
inline int TestDiffMessage::_internal_rm_size() const {
  return rm_.size();
}
inline int TestDiffMessage::rm_size() const {
  return _internal_rm_size();
}
inline void TestDiffMessage::clear_rm() {
  rm_.Clear();
}
inline ::protobuf_unittest::TestField* TestDiffMessage::mutable_rm(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.rm)
  return rm_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >*
TestDiffMessage::mutable_rm() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.rm)
  return &rm_;
}
inline const ::protobuf_unittest::TestField& TestDiffMessage::_internal_rm(int index) const {
  return rm_.Get(index);
}
inline const ::protobuf_unittest::TestField& TestDiffMessage::rm(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.rm)
  return _internal_rm(index);
}
inline ::protobuf_unittest::TestField* TestDiffMessage::_internal_add_rm() {
  return rm_.Add();
}
inline ::protobuf_unittest::TestField* TestDiffMessage::add_rm() {
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.rm)
  return _internal_add_rm();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf_unittest::TestField >&
TestDiffMessage::rm() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.rm)
  return rm_;
}

// repeated .google.protobuf.Any rany = 16;
inline int TestDiffMessage::_internal_rany_size() const {
  return rany_.size();
}
inline int TestDiffMessage::rany_size() const {
  return _internal_rany_size();
}
inline PROTOBUF_NAMESPACE_ID::Any* TestDiffMessage::mutable_rany(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf_unittest.TestDiffMessage.rany)
  return rany_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::Any >*
TestDiffMessage::mutable_rany() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_unittest.TestDiffMessage.rany)
  return &rany_;
}
inline const PROTOBUF_NAMESPACE_ID::Any& TestDiffMessage::_internal_rany(int index) const {
  return rany_.Get(index);
}
inline const PROTOBUF_NAMESPACE_ID::Any& TestDiffMessage::rany(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_unittest.TestDiffMessage.rany)
  return _internal_rany(index);
}
inline PROTOBUF_NAMESPACE_ID::Any* TestDiffMessage::_internal_add_rany() {
  return rany_.Add();
}
inline PROTOBUF_NAMESPACE_ID::Any* TestDiffMessage::add_rany() {
  // @@protoc_insertion_point(field_add:protobuf_unittest.TestDiffMessage.rany)
  return _internal_add_rany();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::Any >&
TestDiffMessage::rany() const {
  // @@protoc_insertion_point(field_list:protobuf_unittest.TestDiffMessage.rany)
  return rany_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf_unittest

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_google_2fprotobuf_2futil_2fmessage_5fdifferencer_5funittest_2eproto
